### ISSUE TITLE
Multiple panes when there should be two

### ISSUE THREAD

**Issue by Hunanbean** [jsartelle/obsidian-auto-split#4]
To reproduce, click on a video in the vault, not from a within a note.
click open  a note, click open the video, click open a note, etc.

notice multiple panes opened.

**Comment by jsartelle** [comment]
Good catch, I don't usually open non-text files in Obsidian. Should be fixed in 1.1.1.

**Comment by Hunanbean** [comment]
Thank you for the timely update. Unfortunately, it is still a problem.
 Have a note open that is auto split. <works across two panes, as it should>
open a video <replaces the note in two panes, as it should>
Open a note <it opens in two panes, as it should, but leaves a third pane open with the video>
open a video <replaces the note in two panes, as it should, third video pane still remains>
Open a note <it opens in two panes, as it should, but leaves a third and fourth pane open with the video in it>

Verified newest version is installed, 1.1.1
also, i had uninstalled Media Extended before testing, just to be sure.
thank you

**Comment by Hunanbean** [comment]
You may need to do that procedure twice to see the issue. It generally works properly the first time you click between them.
It is not limited to video file. A PDF will do the same thing. tested with all other plugins disabled.

**Comment by jsartelle** [comment]
Sorry for the delay! Should be fixed in 1.1.2.

**Comment by Hunanbean** [comment]
1.1.2
Now, when i click on a media file it opens in the two panes as expected, but then i cannot open anything else by clicking on it until i close at least one of the panes :)

Thanks for the continued efforts!

**Comment by jsartelle** [comment]
That appears to be a bug with Media Extended and linked panes. I'm able to reproduce it without this plugin being installed :P

**Comment by Hunanbean** [comment]
Well shoot! Apoligies for any wasted time :/ I am unable to test at this moment, but i am sure you are correct. Thanks a bunch!

**Comment by jsartelle** [comment]
No worries!
